name: PR Tests

on: pull_request

permissions:
  contents: read

jobs:
  tests:
    name: Run Tests
    runs-on: macos-12
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v4
    - name: Build and run tests
      run: ./Scripts/build.sh tests
